### ISSUE TITLE
[EPIC] HTML Mockups for Side Quest Front End

### ISSUE THREAD

**Issue by wvwatson** [dossinstitute/sidequest#18]
Create the HTML Mockups for Side Quest Contracts mentioned in #1 and javascript mentioned in #17
---
Create Node.js repository to serve sidequest html/javascript #21

**Comment by tierra-d** [comment]
https://docs.google.com/document/d/1QdIB3HqCxKDCn2V5KrqLln8sPmoD170OLumXnKYGYgM/edit?usp=sharing
