### ISSUE TITLE
User Registration and Participation

### ISSUE THREAD

**Issue by wvwatson** [dossinstitute/sidequest#3]
### User Registration and Participation

**Description:** Develop functionality for users to register for the quest using their wallet addresses. The contract should track registered users and their interaction status.

**Acceptance Criteria:**

1. Users should be able to register for a quest by providing their wallet address.
2. The contract must keep track of registered users and their interaction statuses.
3. Ensure only valid wallet addresses are accepted for registration.
4. Implement a function to retrieve the registration status of a user for a specific quest.

```
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

contract EventAmbassadorQuest {

    address public admin;

    struct Quest {

        uint256 eventId;

        uint256 startDate;

        uint256 endDate;

        uint256 requiredInteractions;

        string rewardType; // "NFT" or "token"

    }

    struct UserInteraction {

        bool isRegistered;

        uint256 interactionsCount;

    }

    mapping(uint256 => Quest) public quests;

    mapping(uint256 => mapping(address => UserInteraction)) public userInteractions;

    event QuestCreated(uint256 eventId, uint256 startDate, uint256 endDate, uint256 requiredInteractions, string rewardType);

    event UserRegistered(uint256 eventId, address user);

    modifier onlyAdmin() {

        require(msg.sender == admin, "Only admin can perform this action");

        _;

    }

    constructor() {

        admin = msg.sender;

    }

    function createQuest(

        uint256 _eventId, 

        uint256 _startDate, 

        uint256 _endDate, 

        uint256 _requiredInteractions, 

        string memory _rewardType

    ) public onlyAdmin {

        require(_requiredInteractions >= 3, "Required interactions must be at least three");

        require(bytes(_rewardType).length > 0, "Reward type must be specified");

        quests[_eventId] = Quest({

            eventId: _eventId,

            startDate: _startDate,

            endDate: _endDate,

            requiredInteractions: _requiredInteractions,

            rewardType: _rewardType

        });

        emit QuestCreated(_eventId, _startDate, _endDate, _requiredInteractions, _rewardType);

    }

    function registerForQuest(uint256 _eventId) public {

        require(quests[_eventId].eventId != 0, "Quest does not exist");

        require(!userInteractions[_eventId][msg.sender].isRegistered, "User already registered");

        userInteractions[_eventId][msg.sender] = UserInteraction({

            isRegistered: true,

            interactionsCount: 0

        });

        emit UserRegistered(_eventId, msg.sender);

    }

    function isUserRegistered(uint256 _eventId, address _user) public view returns (bool) {

        return userInteractions[_eventId][_user].isRegistered;

    }

    function getUserInteractionCount(uint256 _eventId, address _user) public view returns (uint256) {

        require(userInteractions[_eventId][_user].isRegistered, "User is not registered for this quest");

        return userInteractions[_eventId][_user].interactionsCount;

    }

}
```
**Acceptance Criteria Validation:**

1. **User Registration Function:**
    * The `registerForQuest` function allows users to register for a quest using their wallet address.
    * Ensures the quest exists and the user is not already registered.
    * Records the user's registration status and initializes their interaction count.
2. **Tracking User Interactions:**
    * The `UserInteraction` struct tracks whether a user is registered and their count of interactions.
    * `userInteractions` mapping stores user interaction data for each quest.
3. **Validation of Wallet Addresses:**
    * Ensures that only valid (non-duplicate) registrations are accepted.
    * Prevents multiple registrations by the same user for the same quest.
4. **Retrieve Registration Status and Interaction Count:**
    * The `isUserRegistered` function checks if a user is registered for a specific quest.
    * The `getUserInteractionCount` function retrieves the number of interactions a registered user has for a specific quest.

This contract component meets the specified requirements, ensuring that users can register for quests and their interaction statuses are tracked appropriately.

**Comment by wvwatson** [comment]
points: 1, 2, 3, 5, 8, 13, 21

@russlive215 
@Fr0z0n3 
@noireconnect2024 
@wvwatson 

points:

**Comment by noireconnect2024** [comment]
![image](https://github.com/dossinstitute/sidequest/assets/149025126/85592265-fb41-4bdd-b1fb-eb92d0ddfc27)

Doesn't open...

**Comment by noireconnect2024** [comment]
![image](https://github.com/dossinstitute/sidequest/assets/149025126/23aec13e-f02d-4558-9707-8bff7d34143c)

For the fields where the user does not have to input any information it might be less confusing if we were to remove that field.
